<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AZM.Abyan.Identity.Application\AZM.Abyan.Identity.Application.csproj" />
    <ProjectReference Include="..\AZM.Abyan.Identity.Infrastructure\AZM.Abyan.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\AZM.Identity.Application\AZM.Abyan.Identity.Application.csproj" />
    <ProjectReference Include="..\AZM.Identity.Infrastructure\AZM.Abyan.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
